repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        files: \.sh
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
        exclude: ^helm/
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
