site_name: BC Gov Common Hosted Single Sign-on
docs_dir: wiki
# TODO: change branch on dev merge
edit_uri: https://github.com/bcgov/sso-keycloak/edit/wiki/wiki/

nav:
  - Home: index.md
  - SSO Onboarding: SSO-Onboarding.md
  - Using Your SSO Client: Using-Your-SSO-Client.md
  - What is Keycloak at BC Government: What-is-Keycloak-at-BC-Government.md
  - Our Partners: the Identity Providers: Our-Partners-the-Identity-Providers.md
  - Creating and Managing a Role: Creating-a-Role.md
  - Useful References: Useful-References.md
  - Pathfinder SSO Uptime: Pathfinder-Uptime-Monitoring.md
  - Alerts and Us: Alerts-and-Us.md
  - Our Service Level: Alerts-and-Us#service-levels
  - Additional Help: Additional-Help.md

plugins:
  - techdocs-core
  - ezlinks
markdown_extensions:
  - attr_list
  - markdown_inline_mermaid
  - md_in_html
  - mkpatcher:
      location: patcher.py
