apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    name: patroni-pdb
  spec:
    minAvailable: 2
    selector:
      matchLabels:
        statefulset: ${STATEFULSET}
parameters:
- name: STATEFULSET
  required: true
  description: the sateful set we will be budgeting
