replicaCount: 3

project: sso-keycloak

image:
  tag: dev

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-patroni
  credentials:
    secret: sso-patroni
    usernameKey: username-superuser
    passwordKey: password-superuser

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
