replicaCount: 5

image:
  tag: 7.4-37

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-master-dev
  credentials:
    secret: sso-pgsql-dev
  admin:
    secret: sso-admin-dev

jgroupCluster:
  secret: sso-jgroups-dev

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
