replicaCount: 5

project: sso-keycloak

image:
  tag: 7.4-37-rc.3

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-test-11-patroni
  database: keycloak
  credentials:
    secret: patroni-11-test-secret
    usernameKey: username
    passwordKey: password

persistentLog:
  storageClassSize: 10Gi

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
