replicaCount: 1

project: sso-keycloak-2
nameOverride: sso-keycloak-2
fullnameOverride: sso-keycloak-2

image:
  tag: 7.5-9-rc.2

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-patroni
  database: ssokeycloak2
  credentials:
    secret: sso-patroni
    usernameKey: username-superuser
    passwordKey: password-superuser

tls:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512M
