replicaCount: 2

image:
  tag: 7.4-37-rc.2

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-patroni
  credentials:
    secret: sso-patroni

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1250m
    memory: 2Gi
