replicaCount: 2

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512M

patroni:
  install: true
  replicaCount: 2

  persistentVolume:
    size: 2Gi

  podDisruptionBudget:
    enabled: true
