replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.5-build.3
  pullPolicy: IfNotPresent

rollingUpdate:
  maxSurge: "100%"
  maxUnavailable: 0

configuration:
  enabled: true
  version: "7.6"

project: sso-keycloak
nameOverride: sso-keycloak-2
fullnameOverride: sso-keycloak-2

postgres:
  host: sso-patroni
  database: ssokeycloak2
  credentials:
    secret: sso-patroni-appusers
    usernameKey: username-appuser2
    passwordKey: password-appuser2

tls:
  enabled: false

networkPolicies:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512M
