replicaCount: 1

project: sso-keycloak

image:
  tag: 7.5-9-rc.2

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-patroni
  credentials:
    secret: sso-patroni
    usernameKey: username-superuser
    passwordKey: password-superuser

tls:
  enabled: true

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
