replicaCount: 2

image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.5-build.30
  pullPolicy: IfNotPresent

rollingUpdate:
  maxSurge: '100%'
  maxUnavailable: 0

configuration:
  enabled: true
  version: '7.6'

annotations:
  timeout: 90s

project: sso-keycloak
nameOverride: sso-keycloak
fullnameOverride: sso-keycloak

additionalServerOptions: '-Dkeycloak.profile.feature.impersonation=disabled -Djboss.persistent.log.dir=/var/log/eap'

tls:
  enabled: true

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512M

livenessProbe:
  enabled: true
  verification: script
  initialDelaySeconds: 240
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6

readinessProbe:
  enabled: true
  verification: script
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6

maintenancePage:
  enabled: false
  active: false

patroni:
  replicaCount: 2

  persistentVolume:
    size: 1Gi

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: false

service:
  type: ClusterIP
  port: 8443
