replicaCount: 5

image:
  tag: 7.4-37-rc.2

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-master-test
  credentials:
    secret: sso-pgsql-test
  admin:
    secret: sso-admin-test

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
