replicaCount: 7

project: sso-keycloak

image:
  tag: 7.4-37-rc.3

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-prod-11-patroni
  database: rhsso
  credentials:
    secret: patroni-11-prod-secret
    usernameKey: username
    passwordKey: password

annotations:
  timeout: 90s

persistentLog:
  storageClassSize: 15Gi

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
