replicaCount: 2

image:
  tag: 7.4-37-rc.1

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-master-test
  credentials:
    secret: sso-pgsql-test
  admin:
    secret: sso-admin-test

jgroupCluster:
  secret: sso-jgroups-test

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1250m
    memory: 2Gi
