replicaCount: 5

project: sso-keycloak

image:
  tag: 7.4-37-rc.3

service:
  type: ClusterIP
  port: 8443

postgres:
  # host: sso-pgsql-master-dev
  host: sso-pgsql-dev-11-patroni
  database: rhsso
  credentials:
    secret: patroni-11-dev-secret
    usernameKey: username
    passwordKey: password

    # secret: sso-pgsql-dev-11-patroni-appusers
    # usernameKey: username-appuser1
    # passwordKey: password-appuser1

persistentLog:
  storageClassSize: 10Gi

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
