replicaCount: 1

image:
  tag: 7.6.2-build.2
  pullPolicy: IfNotPresent

project: sso-keycloak
nameOverride: sso-keycloak-5
fullnameOverride: sso-keycloak-5

postgres:
  host: sso-patroni
  database: ssokeycloak5
  credentials:
    secret: sso-patroni-appusers
    usernameKey: username-appuser5
    passwordKey: password-appuser5

tls:
  enabled: false

networkPolicies:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512M
