replicaCount: 1

image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.5-build.21
  pullPolicy: IfNotPresent

rollingUpdate:
  maxSurge: "100%"
  maxUnavailable: 0

configuration:
  enabled: true
  version: "7.6"

project: sso-keycloak
nameOverride: sso-keycloak-5
fullnameOverride: sso-keycloak-5

postgres:
  host: sso-patroni
  database: ssokeycloak5
  credentials:
    secret: sso-patroni-appusers
    usernameKey: username-appuser5
    passwordKey: password-appuser5

tls:
  enabled: false

networkPolicies:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 512M
