replicaCount: 5

image:
  tag: 7.4-37-rc.3

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-master-dev
  credentials:
    secret: sso-pgsql-dev
    adminUsername: sso
    passwordKey: app-db-password

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
