replicaCount: 7

project: sso-keycloak

image:
  tag: 7.4-37-rc.3

service:
  type: ClusterIP
  port: 8443

postgres:
  host: sso-pgsql-master-prod
  database: rhsso
  credentials:
    secret: sso-pgsql-prod
    usernameKey: app-db-username
    passwordKey: app-db-password

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1250m
    memory: 4Gi
