replicaCount: 2

image:
  tag: 7.4-37-rc.2

service:
  type: ClusterIP
  port: 8443

nameOverride: sso-keycloak
fullnameOverride: sso-keycloak

postgres:
  host: sso-pgsql-master-test
  dbName: rhsso
  credentials:
    secret: patroni-test-jon
    adminUsername: postgres
    passwordKey: password-superuser

tls:
  enabled: true

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1250m
    memory: 2Gi
