FROM maven:3.9.9-eclipse-temurin-21 AS extensions-builder

COPY ./extensions-26 /tmp/
WORKDIR /tmp/
RUN mvn -B clean package --file pom.xml

FROM registry.redhat.io/rhbk/keycloak-rhel9:26.0-6 AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

# un-comment when dataset required for loadtests
COPY ./dataset-providers/keycloak-benchmark-dataset-0.15-SNAPSHOT.jar /opt/keycloak/providers

COPY --from=extensions-builder /tmp/services/target/bcgov-services-1.0.0.jar /opt/keycloak/providers/

WORKDIR /opt/keycloak

# copy the theme directory to `/opt/keycloak/themes/` for now, but we can consider to archive to be deployed later.
COPY ./extensions-26/themes/src/main/resources/theme /opt/keycloak/themes

COPY ./configuration/26/keycloak.conf /opt/keycloak/conf

COPY ./configuration/26/quarkus.properties /opt/keycloak/conf

COPY ./configuration/26/keycloak-default-user-profile.json /tmp

RUN /opt/keycloak/bin/kc.sh build

# change these values to point to a running postgres instance
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
