kind: Template
apiVersion: v1
objects:
  - apiVersion: batch/v1
    kind: Job
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: k6-config
              configMap:
                name: k6-config
          containers:
            - image: ${IMAGE_REPOSITORY}:${IMAGE_TAG}
              name: ${NAME}
              env:
                - name: K6_OUT
                  value: 'timescaledb=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 500Mi
              volumeMounts:
                - name: k6-config
                  mountPath: /var/opt/config
          restartPolicy: Never
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        component: ${NAME}-job
parameters:
  - name: NAME
    value: sso-k6
  - name: IMAGE_TAG
    value: latest
  - name: IMAGE_REPOSITORY
    value: ghcr.io/bcgov/sso-k6
  - name: HTTP_DEBUG
    description: enable http debug logging in the k6 pod
    value: 'false'
  - name: DB_USER
    value: ''
  - name: DB_PASSWORD
    value: ''
  - name: DB_NAME
    value: 'k6loadtests'
  - name: DB_HOST
    value: 'k6-patroni'
  - name: DB_PORT
    value: '5432'
