apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: metabase
    template: metabase-postgresql-template
  name: {{ .Values.metabaseServiceName }}
spec:
  tags:
  - from:
      kind: DockerImage
      name: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    generation: 2
    name: latest
    referencePolicy:
      type: Source
