apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: metabase
    template: metabase-postgresql-template
  name: {{ .Values.metabase_service_name }}
spec:
  tags:
  - from:
      kind: DockerImage
      name: {{ .Values.metabase_image }}
    generation: 2
    name: latest
    referencePolicy:
      type: Source
