apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{ include "metabase.labels" . | nindent 4 }}
  name: {{ .Values.metabaseServiceName }}-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
