apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: metabase
    service: {{ .Values.metabaseServiceName }}
    template: metabase-postgresql-template
  name: {{ .Values.metabaseServiceName }}-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresqlVolumeCapacity }}
