apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: metabase
    service: {{ .Values.metabase_service_name }}
    template: metabase-postgresql-template
  name: {{ .Values.metabase_service_name }}-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql_volume_capacity }}
