apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels: {{ include "metabase.labels" . | nindent 4 }}
  name: {{ .Values.metabaseServiceName }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.metabaseServiceName }}
