apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "metabase.labels" . | nindent 4 }}
  name: {{ .Values.metabaseServiceName }}-postgresql-credentials
stringData:
  database: {{ .Values.postgresqlDatabase }}
  password: {{ .Values.postgresqlPassword }}
  username: {{ .Values.postgresqlUser }}
type: Opaque
