apiVersion: v1
kind: Secret
metadata:
  labels:
    app: metabase
    service: {{ .Values.metabase_service_name }}
    template: metabase-postgresql-template
  name: {{ .Values.metabase_service_name }}-postgresql-credentials
stringData:
  database: {{ .Values.postgresql_database }}
  password: {{ .Values.postgresql_password }}
  username: {{ .Values.postgresql_user }}
type: Opaque
