apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "metabase.labels" . | nindent 4 }}
  name: {{ .Values.metabaseServiceName }}-postgresql-credentials
stringData:
  database: {{ .Values.postgresql.database }}
  password: {{ .Values.postgresql.password }}
  username: {{ .Values.postgresql.user }}
type: Opaque
