apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: metabase
    service: {{ .Values.metabase_service_name }}
    template: metabase-postgresql-template
  name: {{ .Values.metabase_service_name }}
