apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: http://{.spec.clusterIP}:{.spec.ports[?(.name=="{{ .Values.metabaseServiceName }}")].port}
  labels: {{ include "metabase.labels" . | nindent 4 }}
  name: {{ .Values.metabaseServiceName }}
spec:
  ports:
  - name: {{ .Values.metabaseServiceName }}
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: metabase
    deploymentconfig: {{ .Values.metabaseServiceName }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="{{ .Values.metabaseServiceName }}-postgresql")].port}
  labels:
    app: metabase
    template: metabase-postgresql-template
  name: {{ .Values.metabaseServiceName }}-postgresql
spec:
  ports:
  - name: {{ .Values.metabaseServiceName }}-postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: {{ .Values.metabaseServiceName }}-postgresql
  sessionAffinity: None
  type: ClusterIP
