apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: http://{.spec.clusterIP}:{.spec.ports[?(.name=="{{ .Values.metabase_service_name }}")].port}
  labels:
    app: metabase
    service: {{ .Values.metabase_service_name }}
    template: metabase-postgresql-template
  name: {{ .Values.metabase_service_name }}
spec:
  ports:
  - name: {{ .Values.metabase_service_name }}
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: metabase
    deploymentconfig: {{ .Values.metabase_service_name }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="{{ .Values.metabase_service_name }}-postgresql")].port}
  labels:
    app: metabase
    template: metabase-postgresql-template
  name: {{ .Values.metabase_service_name }}-postgresql
spec:
  ports:
  - name: {{ .Values.metabase_service_name }}-postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: {{ .Values.metabase_service_name }}-postgresql
  sessionAffinity: None
  type: ClusterIP
