kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-secret
    type: Opaque
    stringData:
      admin-username: ${ADMIN_USERNAME}
      admin-password: ${ADMIN_PASSWORD}
      ches-client-id: ${CHES_CLIENT_ID}
      ches-client-secret: ${CHES_CLIENT_SECRET}
      ches-token-url: ${CHES_TOKEN_URL}
      mail-server: ${MAIL_SERVER}
  - apiVersion: batch/v1
    kind: Job
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: ${IMAGE_REPOSITORY}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              resources:
                limits:
                  cpu: 2
                  memory: 5Gi
                requests:
                  cpu: 500m
                  memory: 500Mi
              env:
                - name: MAIL_SERVER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-secret
                      key: mail-server
                - name: CHES_TOKEN_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-secret
                      key: ches-token-url
                - name: CHES_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-secret
                      key: ches-client-id
                - name: CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-secret
                      key: ches-client-secret
                - name: ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-secret
                      key: admin-username
                - name: ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-secret
                      key: admin-password
                - name: RECEPIENT
                  value: ${RECEPIENT}
                - name: SCENARIO
                  value: ${SCENARIO}
                - name: SERVER_URL
                  value: ${SERVER_URL}
                - name: ADDITIONAL_CONFIG
                  value: ${ADDITIONAL_CONFIG}
          restartPolicy: Never
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        component: ${NAME}-job
parameters:
  - name: NAME
    description: The name of the job
  - name: IMAGE_TAG
    value: dev
  - name: IMAGE_REPOSITORY
    value: ghcr.io/bcgov/sso-benchmark-runner
  - name: KEYCLOAK_BENCHMARK_VERSION
    value: keycloak-benchmark-0.15-SNAPSHOT
  - name: SCENARIO
    description: The scenario to run
    default: 'keycloak.scenario.authentication.ClientSecret'
  - name: SERVER_URL
    description: The URL of the Keycloak server
  - name: ADMIN_USERNAME
    description: The admin username
  - name: ADMIN_PASSWORD
    description: The admin password
  - name: ADDITIONAL_CONFIG
    description: Configuration set of parameters for the test
  - name: CHES_CLIENT_ID
    description: The CHES client ID
  - name: CHES_CLIENT_SECRET
    description: The CHES client secret
  - name: CHES_TOKEN_URL
    description: The CHES token URL
  - name: MAIL_SERVER
    description: The mail server
  - name: RECEPIENT
    description: The email address to send the report to
