.PHONY: single-realm-active-sessions
single-realm-active-sessions:
	k6 run singleRealmActiveSessions.js

.PHONY: multi-realm-active-sessions
multi-realm-active-sessions:
	k6 run multiRealmActiveSessions.js
