apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: initdb
          image: postgres:11.6-alpine
          command: ["bash", "-c"]
          args:
            - |
              echo starting;
              set -euo pipefail;
              echo "select 'create database $PGDATABASE_NAME' where NOT exists (select from pg_database where datname = '$PGDATABASE_NAME')\gexec" | psql -d postgres
              psql -d $PGDATABASE_NAME -qtA --set ON_ERROR_STOP=1 <<EOF
                create table if not exists public.rosters (
                    id serial not null,
                    realm varchar(1000),
                    product_name varchar(1000),
                    openshift_namespace varchar(1000),
                    product_owner_email varchar(1000),
                    product_owner_idir_userid varchar(1000),
                    technical_contact_email varchar(1000),
                    technical_contact_idir_userid varchar(1000),
                    created_at timestamp with time zone default current_timestamp,
                    updated_at timestamp with time zone default current_timestamp,
                    primary key(id)
                );

                create table if not exists public.surveys_1 (
                    idir_userid varchar(1000),
                    contact_email varchar(1000),
                    willing_to_move varchar(1000),
                    when_to_move varchar(1000),
                    created_at timestamp with time zone default current_timestamp,
                    primary key(idir_userid)
                );
              EOF
          env:
            - name: PGHOST
              value: {{ .Values.postgres.host }}
            - name: PGPORT
              value: {{ .Values.postgres.port | quote }}
            - name: PGUSER
              value: {{ .Values.postgres.user }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.password.secret }}
                  key: {{ .Values.postgres.password.key }}
            - name: PGDATABASE_NAME
              value: {{ .Values.postgres.database }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: SSO_URL
              value: {{ .Values.sso.url }}
            - name: SSO_CLIENT_ID
              value: {{ .Values.sso.clientId }}
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.clientSecret.secret }}
                  key: {{ .Values.sso.clientSecret.key }}
            - name: SSO_REDIRECT_URI
              value: {{ .Values.sso.redirectUri }}
            - name: SSO_LOGOUT_REDIRECT_URI
              value: {{ .Values.sso.logoutRedirectUri }}
            - name: SSO_AUTHORIZATION_RESPONSE_TYPE
              value: {{ .Values.sso.authorizationResponseType }}
            - name: SSO_AUTHORIZATION_SCOPE
              value: {{ .Values.sso.authorizationScope }}
            - name: SSO_TOKEN_GRANT_TYPE
              value: {{ .Values.sso.tokenGrantType }}
            - name: JWT_SECRET
              {{- if .Values.jwt.secret }}
              value: {{ .Values.jwt.secret }}
              {{- else }}
              value: {{ randAlphaNum 32 | b64enc | quote }}
              {{- end }}
            - name: JWT_TOKEN_EXPIRY
              value: {{ .Values.jwt.tokenExpiry }}
            - name: PGHOST
              value: {{ .Values.postgres.host }}
            - name: PGPORT
              value: {{ .Values.postgres.port | quote }}
            - name: PGUSER
              value: {{ .Values.postgres.user }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.password.secret }}
                  key: {{ .Values.postgres.password.key }}
            - name: PGDATABASE
              value: {{ .Values.postgres.database }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
