version: '3.8'

services:
  siteminder-tests:
    image: siteminder-tests:latest
    container_name: siteminder-tests
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      CLUSTER: ${CLUSTER}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
