{{ $root := . }}
{{- range .Values.opaque }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "..name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "..chart" $ }}
type: Opaque
data:
  {{- range $key, $value := . }}
  {{- if ne  $key "name" }}
  {{ $key }}: '{{ $root.Files.Get $value | b64enc }}'
  {{- end }}
  {{- end }}
{{- end }}
