image:
  repository: ghcr.io/bcgov/kc-cron-job
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: kc-cron-job
fullnameOverride: kc-cron-job

namespace: '6d70e7-tools'

pgHost: kc-cron-patroni.6d70e7-tools.svc.cluster.local
