image:
  repository: ghcr.io/bcgov/kc-cron-job
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: kc-cron-job
fullnameOverride: kc-cron-job

namespace: "3d5c3f-tools"

pgHost: kc-cron-patroni.3d5c3f-tools.svc.cluster.local
