nameOverride: k6-patroni

fullnameOverride: k6-patroni

image:
  # see https://github.com/zalando/spilo/releases
  repository: ghcr.io/zalando/spilo-16
  pullPolicy: Always
  tag: 3.2-p3 # timescaledb 2.14.X

replicaCount: 2

postgresMajorVersion: 16

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podDisruptionBudget:
  enabled: false

persistentVolume:
  size: 500Mi
