name: Gold Custom Request
description: File a gold custom request
title: "[Gold Custom]: "
labels: ["gold", "custom"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: po-contact
    attributes:
      label: Product Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: to-contact
    attributes:
      label: Technical Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: existing-realm
    attributes:
      label: Silver custom realm name
      description: what is your realm name
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: textarea
    id: new-realm-name
    attributes:
      label: Name your new Gold custom realm
      description: Make it meaningful, unique and less than 10 characters
      placeholder:  myrealm
      value: "myrealm"
    validations:
      required: true
 Note 1  we will have some information on IDP and mapping to CSS APP
 Note 2 limitation on our event logs at this time
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
