name: Gold Custom Request
description: File a gold custom request
title: "[Gold Custom]: "
labels: ["gold", "custom"]
assignees:
  - octocat 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: po-contact
    attributes:
      label: Product Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: to-contact
    attributes:
      label: Technical Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
- type: dropdown
    id: existing-realm
    attributes:
      label: Silver custom realm name
      description: what is your realm name
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
 - type: input
    id: new-realm-name
    attributes:
      label: New realm name
      description: new realm name syntax less that 10 characters and a meaningful name
      placeholder: ex. myrealmname
    validations:
      required: true          
 - type: markdown
    attributes:
      value: |
        Will have info on IDP and assoicated CSS App & Event Log as upcoming 
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
