name: Gold Custom Request
description: File a gold custom request
title: "[Gold Custom]: "
labels: ["gold", "custom"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please reachout to us if you have any questions:  bcgov.sso@gov.bc.ca  or [rocketchat](https://chat.developer.gov.bc.ca/channel/sso)
  - type: input
    id: po-contact
    attributes:
      label: Product Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: to-contact
    attributes:
      label: Technical Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: 2-to-contact
    attributes:
      label: Secondary Technical Owner Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: existing-realm
    attributes:
      label: Silver custom realm name
      description: Please pick your SILVER custom realm name from the list below
      options:
        - ff09qn3f
        - 4qjrpzzl
        - v4mbqqas
        - jxoe2o46
        - umafubc9
        - cp1qly2d
        - 5k8dbl4h
        - gzyg46lx
        - 8gyaubg
        - fcf0kpqr
        - vtkayq4c
        - kmas316h
        - 3nwwef1
        - 4piqfpfu
        - gde0rjxl
        - digitaltrust
        - g7v0xlf4
        - jbd6rnxw
        - rzh2zkjq
    validations:
      required: true
  - type: input
    id: new-realm-name
    attributes:
      label: New realm name
      description: new realm name syntax less that 10 characters and a meaningful name. Please note that if there are any duplicate names, we will ask you to resubmit with another name.
      placeholder: ex. myrealmname
    validations:
      required: true
  - type: checkboxes
    id: gold-env
    attributes:
      label: Gold environment needed
      description: Which env
      options:
      - label: Dev
      - label: Test
      - label: Prod
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional Information ##
        Please create your IDP via our [Common Hosted Single Sign on App](https://bcgov.github.io/sso-requests) 
        [How to guide can be found here](https://stackoverflow.developer.gov.bc.ca/questions/864) 
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Gold Custom Realm Agreement](https://github.com/bcgov/sso-keycloak/wiki/Gold-Custom-Realm-Service-Agreement)
      options:
        - label: I agree to follow Pathfinder SSO's Gold Custom Realm Agreement
          required: true
