apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
    project: {{ include "..project" . }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    {{ if .Values.tls.enabled }}
    termination: reencrypt
    {{ else }}
    termination: edge
    {{ end }}
  to:
    kind: Service
    name: {{ include "..fullname" . }}
