apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{- if .Values.credentials.random }}
  admin: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  admin: {{ .Values.credentials.superuser | b64enc }}
  {{- end }}
