apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app: {{ include "..fullname" . }}
    chart: {{ include "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{- if .Values.credentials.random }}
  password-admin: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  password-admin: {{ .Values.credentials.admin | b64enc }}
  {{- end }}
