apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-keycloak.fullname" . }}-admin-secret
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  password-admin: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-keycloak.fullname" . }}-jgroups
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  cluster-password: {{ randAlphaNum 32 | b64enc | quote }}
