apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-keycloak.fullname" . }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.enabled }}
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.tls.httpsSecret }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      {{ if .Values.tls.enabled }}
      name: https
      targetPort: https
      {{ else }}
      name: http
      targetPort: http
      {{ end }}
  selector: {{ include "sso-keycloak.selectorLabels" . | nindent 4 }}
