{{- if .Values.pingService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-ping
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.tls.enabled }}
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.tls.jgroupsSecret }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.pingService.port }}
      name: ping
      targetPort: ping
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
