# Install Patroni
# Install oc
# Install helm?
# Create secret for gold and golddr patroni instance 
# Log into gold
# Run patroni install
# Log into golddr
# Run patroni dr install

# Switchover agen
# log into golddr
# rsh into patroni
# use REST API to swith config
# log into golddr
# 

# # variables 
# - openshift url gold
# - openshift token gold
# - openshift url golddr
# - openshift token golddr

name: Deploy patroni to gold and golddr

inputs: 
  openshift_server_url:
    description: "URL of the OpenShift server"
    required: true
  openshift_token:
    description: "Unique login token for OpenShift"
    required: true  
  namespace:
    description: "The namespace being deployed to"
    required: true
  values_file:
    description: "The values file used by helm"
    required: true
  name: 
    description: "The name of the service being built"
    required: true
  


runs:
  using: composite
  steps:
  - name: Authenticate, set context, and run deploy script
    uses: redhat-actions/oc-login@v1
    with:
      openshift_server_url: ${{ inputs.openshift_server_url }}
      openshift_token: ${{ inputs.openshift_token }}
      namespace: ${{ inputs.namespace }}
      insecure_skip_tls_verify: true
  - run: |
      kubectl create secret generic <secret-name> -n <my-namespace> \
        --from-literal=username-superuser=postgres \
        --from-literal=username-admin=admin \
        --from-literal=username-standby=standby \
        --from-literal=username-appuser= appuser \
        --from-literal=password-superuser= ${{ inputs.password_superuser}} \
        --from-literal=password-admin= ${{ inputs.password_admin }} \
        --from-literal=password-standby=${{ inputs.password_standby }} \
        --from-literal=password-appuser=${{ inputs.password_appuser }}
      chmod +x ./lib/helm_patroni_deploy.sh
      ./lib/helm_patroni_deploy.sh \
        ${{ inputs.name }} . \
        -n ${{ inputs.namespace }} \
        -f values.yaml \
        -f values-${{ inputs.namespace }}-${{ inputs.name }}.yaml
      oc get secret sso-patroni -o yaml > sso-patroni.yaml
    shell: bash
  # - name: Copy patroni secret to send to golddr
  #   run: | 
  #     oc get secret sso-patroni -o yaml > sso-patroni.yaml
  # - name: Authenticate, set context, and run deploy script golddr
  #   uses: redhat-actions/oc-login@v1
  #   with:
  #     openshift_server_url: ${{ inputs.openshift_server_url_gold_dr }}
  #     openshift_token: ${{ inputs.openshift_token_gold_dr }}
  #     namespace: ${{ inputs.namespace }}
  #     insecure_skip_tls_verify: true
  # - name: Apply secret to 

# Idea: set the standby_host, standby_port, and replica count using --set instead of values file 
# Idea: set up the network policies and tsc if necessary
