# Install Patroni
# Install oc
# Install helm?
# Create secret for gold and golddr patroni instance 
# Log into gold
# Run patroni install
# Log into golddr
# Run patroni dr install

# Switchover agen
# log into golddr
# rsh into patroni
# use REST API to swith config
# log into golddr
# 

# # variables 
# - openshift url gold
# - openshift token gold
# - openshift url golddr
# - openshift token golddr

name: Deploy patroni to gold and golddr

inputs: 
  openshift_server_url:
    description: "URL of the OpenShift server"
    required: true
  openshift_token:
    description: "Unique login token for OpenShift"
    required: true  
  namespace:
    description: "The namespace being deployed to"
    required: true
  values_file:
    description: "The values file used by helm"
    required: true
  name: 
    description: "The name of the service being built"
    required: true
  password_superuser:
    description: "Patroni password"
    required: true
  password_admin:
    description: "Patroni password"
    required: true
  password_standby:
    description: "Patroni password"
    required: true
  password_appuser:
    description: "Patroni password"
    required: true
  openshift_server_golddr_url:
    description: "URL of the OpenShift Golddr server"
    required: true
  openshift_token_golddr:
    description: "Unique login token for Golddr OpenShift"
    required: true   


runs:
  using: composite
  steps:
  - name: Log into golddr and remove patroni standby
    uses: redhat-actions/oc-login@v1
    with:
      openshift_server_url: ${{ inputs.openshift_server_golddr_url }}
      openshift_token: ${{ inputs.openshift_token_golddr }}
      namespace: ${{ inputs.namespace }}
      insecure_skip_tls_verify: true
  - run: |
      echo "Line one"
      echo 'Line two'
      echo "Line three"
      chmod +x ./lib/patroni_dr_to_active.sh
      ./lib/patroni_dr_to_active.sh 
  # oc rsh -n ${{ inputs.namespace }} sso-patroni-0
  # curl -s -XPATCH -d '{  "standby_cluster":null}' http://localhost:8008/config | jq .
  # exit
    shell: bash
  # - name: Copy patroni secret to send to golddr
  #   run: | 
  #     oc get secret sso-patroni -o yaml > sso-patroni.yaml
  # - name: Authenticate, set context, and run deploy script golddr
  #   uses: redhat-actions/oc-login@v1
  #   with:
  #     openshift_server_url: ${{ inputs.openshift_server_url_gold_dr }}
  #     openshift_token: ${{ inputs.openshift_token_gold_dr }}
  #     namespace: ${{ inputs.namespace }}
  #     insecure_skip_tls_verify: true
  # - name: Apply secret to 

# Idea: set the standby_host, standby_port, and replica count using --set instead of values file 
# Idea: set up the network policies and tsc if necessary
