apiVersion: v1
name: patroni
description: "Highly available elephant herd: HA PostgreSQL cluster."
version: 0.17.8
appVersion: 1.5-p5
home: https://github.com/zalando/patroni
sources:
  - https://github.com/zalando/patroni
  - https://github.com/zalando/spilo
