version: '3'

volumes:
  postgres_data:
    driver: local
  log_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: testauth
    environment:
      DB_POSTGRESQL_SERVICE_HOST: postgres
      DB_POSTGRESQL_SERVICE_PORT: 5432
      DB_USERNAME: keycloak
      DB_PASSWORD: password
      DB_DATABASE: keycloak
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      TZ: America/Vancouver
      JAVA_OPTS_APPEND: '-Djboss.persistent.log.dir=/opt/eap'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - log_data:/opt/eap:rw
