dockerconfig: []
# dockerconfig:
#   - name: gh-registry-config
#     registry: ghcr.io
#     username:
#     password:

opaque: []
# see https://docs.openshift.com/container-platform/4.1/networking/routes/secured-routes.html#nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate_secured-routes
# opaque:
#   - name: sso-keycloak-oidc-gov-bc-ca-cert
#     key: example.key
#     certificate: example.cert
#     caCertificate: example-ca.cert
#     destinationCACertificate: example-dest-ca.cert
