image:
  repository:  ghcr.io/bcgov/kc-cron-job
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: kc-cron-job
fullnameOverride: kc-cron-job

namespace: "3d5c3f-dev"

resources:
  limits:
    cpu: 0.5
    memory: 1.5Gi
  requests:
    cpu: 0.25
    memory: 1Gi
