image:
  repository: ghcr.io/bcgov/kc-cron-job
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: kc-cron-job
fullnameOverride: kc-cron-job

namespace:
  eventLogs: "3d5c3f-prod"
  activeSessions: "3d5c3f-tools"

pvc:
  name: sso-keycloak-logs

networkPolicy:
  environment: tools
  licensePlate: 3d5c3f

pgHost: kc-cron-patroni.3d5c3f-tools.svc.cluster.local

resources:
  limits:
    cpu: 0.5
    memory: 512M
  requests:
    cpu: 0.25
    memory: 256M
