image:
  repository: ghcr.io/bcgov/kc-cron-job
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: gh-registry-config

nameOverride: kc-cron-job
fullnameOverride: kc-cron-job

namespace:
  eventLogs: "6d70e7-prod"
  activeSessions: "6d70e7-tools"

pvc:
  name: sso-keycloak-logs

networkPolicy:
  environment: tools
  licensePlate: 6d70e7

pgHost: kc-cron-patroni.6d70e7-tools.svc.cluster.local

resources:
  limits:
    cpu: 0.5
    memory: 512M
  requests:
    cpu: 0.25
    memory: 256M

patroni:
  replicaCount: 2

  nameOverride: kc-cron-patroni
  fullnameOverride: kc-cron-patroni

  persistentVolume:
    size: 50Gi

  podDisruptionBudget:
    enabled: true
