version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: sso-keycloak:24.0.5
    command: start-dev
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_LOG: console
      KC_LOG_LEVEL: DEBUG
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_URL: http://localhost:8080/auth/
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080/auth/
    volumes:
      - ../../docker/keycloak/extensions-24/themes/src/main/resources/theme:/opt/keycloak/themes/

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    restart: on-failure
    tty: true
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
