apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "..fullname" . }}-event-logs
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  # see https://crontab.guru/#0_9_*_*_*
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "..name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          initContainers:
            - name: initdb
              image: postgres:11.6-alpine
              command: ["bash", "-c"]
              args:
                - |
                  echo starting;
                  set -euo pipefail;
                  echo "select 'create database $PGDATABASE_NAME' where NOT exists (select from pg_database where datname = '$PGDATABASE_NAME')\gexec" | psql -d postgres
                  psql -d $PGDATABASE_NAME -qtA --set ON_ERROR_STOP=1 <<EOF

                  EOF
              env:
                - name: PGHOST
                  value: kc-cron-patroni
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-patroni
                      key: password-superuser
                - name: PGDATABASE_NAME
                  value: rhsso
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - node
                - event-logs.js
              env:
                - name: RELEASE_REVISION
                  value: "{{ .Release.Revision }}"
                - name: PGHOST
                  value: kc-cron-patroni.6d70e7-tools.svc.cluster.local
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-patroni.6d70e7-tools.svc.cluster.local
                      key: password-superuser
                - name: PGDATABASE
                  value: rhsso
          restartPolicy: Never
