{{- if .Values.enableRemoveInactiveUsersJob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "..fullname" . }}-rm-inactive-users
  namespace: {{ .Values.namespace.rmInactiveUsers }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  # daily at 2 am pst and 9 am utc
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "..name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          initContainers:
            - name: initdb
              image: postgres:11.6-alpine
              command: ["bash", "-c"]
              args:
                - |
                  echo starting;
                  set -euo pipefail;
                  echo "select 'create database $PGDATABASE' where NOT exists (select from pg_database where datname = '$PGDATABASE')\gexec" | psql -d postgres
                  psql -d $PGDATABASE -qtA --set ON_ERROR_STOP=1 <<EOF
                    create table if not exists public.kc_deleted_vc_users (
                        id serial NOT NULL,
                        timestamp timestamp with time zone default current_timestamp,
                        environment varchar(50),
                        username varchar(255),
                        realm_id varchar(255),
                        attributes jsonb
                    );
                  EOF
              env:
                - name: PGHOST
                  value: kc-cron-patroni
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-patroni
                      key: password-superuser
                - name: PGDATABASE
                  value: rhsso
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - node
                - remove-vc-users.js
              env:
                - name: RELEASE_REVISION
                  value: "{{ .Release.Revision }}"
                - name: PGHOST
                  value: kc-cron-patroni
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-patroni
                      key: password-superuser
                - name: PGDATABASE
                  value: rhsso
                - name: DEV_KEYCLOAK_URL
                  value: https://dev.loginproxy.gov.bc.ca
                - name: DEV_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: dev-kc-client-id
                - name: DEV_KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: dev-kc-client-secret
                - name: TEST_KEYCLOAK_URL
                  value: https://test.loginproxy.gov.bc.ca
                - name: TEST_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: test-kc-client-id
                - name: TEST_KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: test-kc-client-secret
                - name: PROD_KEYCLOAK_URL
                  value: https://loginproxy.gov.bc.ca
                - name: PROD_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: prod-kc-client-id
                - name: PROD_KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: prod-kc-client-secret
                - name: RC_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: rc-webhook
                - name: VC_USERS_RETENTION_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-job-secret
                      key: vc-users-retention-days
          restartPolicy: Never
{{- end }}
