apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "..fullname" . }}-rm-inactive-users
  namespace: {{ .Values.namespace.rmInactiveUsers }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  # daily at 1 am
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "..name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          initContainers:
            - name: initdb
              image: postgres:11.6-alpine
              command: ["bash", "-c"]
              args:
                - |
                  echo starting;
                  set -euo pipefail;
                  echo "select 'create database $PGDATABASE_NAME' where NOT exists (select from pg_database where datname = '$PGDATABASE_NAME')\gexec" | psql -d postgres
                  psql -d $PGDATABASE_NAME -qtA --set ON_ERROR_STOP=1 <<EOF
                    create table if not exists public.kc_deleted_users (
                        id serial NOT NULL,
                        timestamp timestamp with time zone default current_timestamp,
                        environment varchar(50),
                        user_id varchar(50),
                        username varchar(255),
                        email varchar(255),
                        first_name varchar(255),
                        last_name varchar(255),
                        attributes varchar(1000),
                        realm_roles TEXT [],
                        client_roles TEXT [],
                        css_app_deleted BOOLEAN NOT NULL default false
                    );
                  EOF
              env:
                - name: PGHOST
                  value: kc-cron-patroni
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-patroni
                      key: password-superuser
                - name: PGDATABASE
                  value: rhsso
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - node
                - remove-inactive-idir-users.js
              env:
                - name: RELEASE_REVISION
                  value: "{{ .Release.Revision }}"
                - name: PGHOST
                  value: kc-cron-patroni
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-patroni
                      key: password-superuser
                - name: PGDATABASE
                  value: rhsso
                - name: DEV_KEYCLOAK_URL
                  value: https://dev.loginproxy.gov.bc.ca
                - name: DEV_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: dev-kc-client-id
                - name: DEV_KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: dev-kc-client-secret
                - name: TEST_KEYCLOAK_URL
                  value: https://test.loginproxy.gov.bc.ca
                - name: TEST_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: test-kc-client-id
                - name: TEST_KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: test-kc-client-secret
                - name: PROD_KEYCLOAK_URL
                  value: https://loginproxy.gov.bc.ca
                - name: PROD_KEYCLOAK_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: prod-kc-client-id
                - name: PROD_KEYCLOAK_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: prod-kc-client-secret
                - name: BCEID_SERVICE_BASIC_AUTH
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: bceid-service-basic-auth
                - name: BCEID_REQUESTER_IDIR_GUID
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: bceid-requester-idir-guid
                - name: BCEID_SERVICE_ID_DEV
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: bceid-service-id-dev
                - name: BCEID_SERVICE_ID_TEST
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: bceid-service-id-test
                - name: BCEID_SERVICE_ID_PROD
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: bceid-service-id-prod
                - name: CSS_API_URL
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: css-api-url
                - name: CSS_API_AUTH_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: css-api-auth-secret
                - name: RC_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: kc-cron-rm-inactive-users
                      key: rc-webhook
          restartPolicy: Never
