kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cron-job
  namespace: {{ .Values.networkPolicy.licensePlate }}-tools
spec:
  podSelector:
    matchLabels:
      app: kc-cron-patroni
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            environment: {{ .Values.networkPolicy.environment }}
            name: {{ .Values.networkPolicy.licensePlate }}
      - podSelector:
          matchLabels:
            name: {{ .Chart.Name }}
  policyTypes:
    - Ingress
