kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: Allow Cron Job
  namespace: 6d70e7-tools
spec:
  podSelector:
    matchLabels:
      app: kc-cron-patroni
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            environment: {{ .Values.networkPolicy.environment }}
            name: {{ .Values.networkPolicy.licensePlate }}
      - podSelector:
          matchLabels:
            name: {{ .Chart.Name }}
  policyTypes:
    - Ingress
