kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cron-job
  namespace: {{ .Values.networkPolicy.licensePlate }}-tools
spec:
  podSelector:
    matchLabels:
      app: kc-cron-patroni
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            environment: {{ .Values.networkPolicy.environment }}
            name: {{ .Values.networkPolicy.licensePlate }}
      - podSelector:
          matchLabels:
            name: {{ .Chart.Name }}
  policyTypes:
    - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kc-cron-prod-access
  namespace: {{ .Values.networkPolicy.licensePlate }}-tools
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: kc-cron-job
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kc-cron-job
          namespaceSelector:
            matchLabels:
              environment: prod
              name: {{ .Values.networkPolicy.licensePlate }}
  policyTypes:
    - Ingress
