# sso-patroni-knp.yaml
# oc -n c6af30-dev apply -f sso-patroni-knp.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-f5-ingress
  namespace: c6af30-dev
spec:
  podSelector:
    matchLabels:
      name: sso-patroni
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
