nameOverride: "sso-backup-storage"
fullnameOverride: "sso-backup-storage"
backupConfig: |
  postgres=test-patorni-3-patroni:5432/rhsso

  0 1 * * * default ./backup.sh -s
  0 4 * * * default ./backup.sh -s -v all

db:
  secretName: sso-pgsql-prod
  usernameKey: app-db-username
  passwordKey: app-db-password

env:
  DATABASE_SERVICE_NAME:
    value: test-patorni-3-patroni

  ENVIRONMENT_FRIENDLY_NAME:
    value: "Silver SSO sbox-prod DB Backups"

  ENVIRONMENT_NAME:
    value: "sbox"

  TABLE_SCHEMA:
    value: "public"

  DAILY_BACKUPS:
    value: "7"
  WEEKLY_BACKUPS:
    value: "4"
  MONTHLY_BACKUPS:
    value: "1"
