nameOverride: sso-backup-storage
fullnameOverride: sso-backup-storage

image:
  repository: bcgovimages/backup-container
  tag: 2.8.1
  pullPolicy: Always

backupConfig: |
  sso-patroni:5432/ssokeycloak
  0 1 * * * default ./backup.sh -s
  0 4 * * * default ./backup.sh -I -v

db:
  secretName: sso-patroni-appusers
  usernameKey: username-appuser1
  passwordKey: password-appuser1

persistence:
  backup:
    size: 5Gi

env:
  ENVIRONMENT_FRIENDLY_NAME:
    value: 'SSO Sandbox Client Dev Backup'
  ENVIRONMENT_NAME:
    value: e4ca1d-dev
  WEBHOOK_URL:
    value: 'https://chat.developer.gov.bc.ca/hooks/642b1268afe0d4a0674f5a9e/WXcjM9Xg7PLAgnGwFpfix7LEupSrgC87SvieyEDWNFKKETJ9'
    secure: true

  DAILY_BACKUPS:
    value: '3'
  WEEKLY_BACKUPS:
    value: '2'
  MONTHLY_BACKUPS:
    value: '1'
