nameOverride: "metabase-backup-storage"
fullnameOverride: "metabase-backup-storage"

backupConfig: |
  postgres=metabase-postgresql:5432/metabase
  0 1 * * * default ./backup.sh -s
  0 4 * * * default ./backup.sh -s -v all

db:
  secretName: metabase-postgresql-credentials
  usernameKey: username
  passwordKey: password
