nameOverride: "sso-backup-storage"
fullnameOverride: "sso-backup-storage"

image:
  repository: ghcr.io/bcgov/backup-storage
  tag: postgres-13
  pullPolicy: Always

backupConfig: |
  postgres=sso-pgsql-dev-11-patroni:5432/rhsso

  0 1 * * * default ./backup.sh -s
  # 0 4 * * * default ./backup.sh -s -v all

db:
  secretName: patroni-11-dev-secret
  usernameKey: username
  passwordKey: password

env:
  DATABASE_SERVICE_NAME:
    value: sso-pgsql-dev-11-patroni

  ENVIRONMENT_FRIENDLY_NAME:
    value: "Silver SSO production-dev DB Backups"

  DATABASE_SERVER_TIMEOUT:
    value: 500

  ENVIRONMENT_NAME:
    value: "production-dev"

  WEBHOOK_URL:
    value: "<<WEBHOOK URL FOR ROCKETCHAT>>"
    secure: true

  TABLE_SCHEMA:
    value: "public"

  DAILY_BACKUPS:
    value: "7"
  WEEKLY_BACKUPS:
    value: "4"
  MONTHLY_BACKUPS:
    value: "1"
