# The command to restore the latest backup is:
# ./backup.sh -r metabase-postgresql:5432/metabase
# The command to update the backup in sandbox dev is:
# make install NAME=metabase-backup NAMESPACE=eb75ad-tools
nameOverride: "metabase-backup-storage"
fullnameOverride: "metabase-backup-storage"

backupConfig: |
  postgres=metabase-postgresql:5432/metabase
  0 1 * * * default ./backup.sh -s
  0 4 * * * default ./backup.sh -s -v all

db:
  secretName: metabase-postgresql-credentials
  usernameKey: username
  passwordKey: password

persistence:
  backup:
    size: 1Gi
