nameOverride: sso-backup-storage
fullnameOverride: sso-backup-storage

image:
  repository: ghcr.io/bcgov/backup-storage
  tag: postgres-13
  pullPolicy: Always

backupConfig: |
  sso-patroni:5432/ssokeycloak
  0 1 * * * default ./backup.sh -s

db:
  secretName: sso-patroni
  usernameKey: username-appuser
  passwordKey: password-appuser

env:
  ENVIRONMENT_FRIENDLY_NAME:
    value: "SSO Gold Client Production Backup"
  ENVIRONMENT_NAME:
    value: eb75ad-prod
  WEBHOOK_URL:
    value: <<Insert value>>
    secure: true
