nameOverride: "sso-backup-storage"
fullnameOverride: "sso-backup-storage"
backupConfig: |
  postgres=sso-pgsql-master-prod:5432/rhsso

  0 1 * * * default ./backup.sh -s
  0 4 * * * default ./backup.sh -s -v all

db:
  secretName: sso-pgsql-prod
  usernameKey: app-db-username
  passwordKey: app-db-password

env:
  DATABASE_SERVICE_NAME:
    value: sso-pgsql-master-prod

  ENVIRONMENT_FRIENDLY_NAME:
    value: "Silver SSO sbox-prod DB Backups"

  ENVIRONMENT_NAME:
    value: "sbox"

  TABLE_SCHEMA:
    value: "public"
