nameOverride: "sso-backup-storage"
fullnameOverride: "sso-backup-storage"

image:
  repository: ghcr.io/bcgov/backup-storage
  tag: postgres-13

backupConfig: |
  sso-patroni:5432/ssokeycloak
  0 1 * * * default ./backup.sh -s
  0 4 * * * default ./backup.sh -s -v all

db:
  secretName: sso-patroni
  usernameKey: username-admin
  passwordKey: password-admin

persistence:
  backup:
    size: 1Gi
