name: Deploy patroni to gold with golddr standby

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev", "c6af30-test", "c6af30-prod"]

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: sha-${{ github.sha }}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}

jobs:
  deploy-to-openshift-development:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/workflows/actions/
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}
          namespace: ${{ github.event.inputs.namespace }}
          values_file: "values-c6af30-dev-sso-patroni.yaml"
          name: "sso-patroni"
