name: Publish Keycloak Helm Chart

on:
  push:
    branches:
      - dev

jobs:
  build-and-push-helm:
    runs-on: ubuntu-18.04
    env:
      KEYCLOAK_URL: http://localhost:8080
    steps:
      - uses: actions/checkout@v2

      - name: Store Cypress artifacts
        if: github.ref == 'refs/heads/master'
        env:
          KEYCLOAK_HELM_CHART: /helm/keycloak
        run: |
          rm -rf .git
          cd "$KEYCLOAK_HELM_CHART"
          helm package . -d output
          helm repo index output --url https://bcgov.github.io/sso-keycloak/
          git init
          git config user.name $GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config commit.gpgsign false
          git add .
          git commit -m "initial commit"
          git branch -M helm/keycloak
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/bcgov/sso-keycloak.git"
          git push -uf origin helm/keycloak
