name: Publish Tech Docs

on:
  push:
    branches: [dev]
    paths:
      - 'wiki/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-devhub.yml'

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build TechDocs
        uses: bcgov/devhub-techdocs-publish@stable
        id: build_and_publish
        with:
          publish: 'true'
          # only publish to prod DevHub when changes that triggered the job are in `dev` branch
          production:  ${{ github.ref == 'refs/heads/dev' && 'true' || 'false' }}
          bucket_name: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
          s3_access_key_id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
          s3_secret_access_key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
          s3_region: ${{ secrets.TECHDOCS_AWS_REGION }}
          s3_endpoint: ${{ secrets.TECHDOCS_AWS_ENDPOINT }}
