# https://github.com/bcgov/helm-charts/tree/master/charts/backup-storage#build-the-container-image-using-github-actions
name: Create and publish a devevlopment Backup Storage Image

on: workflow_dispatch

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: bcgov/backup-storage

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the sso-repos
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Checkout backup storage repository
        run: git clone https://github.com/BCDevOps/backup-container.git

      - name: Replace the dockerfile
        run: cp ./docker/backup-container/* ./backup-container/docker

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: backup-container/docker
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:development
          labels: sso-keycloak-backup
