name: Publish Keycloak Helm Chart

on:
  push:
    branches:
      - dev
    paths:
      - "helm/**/Chart.yaml"
      - ".github/workflows/publish-helm-chart.yml"

jobs:
  build-and-push-helm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for gh-pages branch
        run: |
          git ls-remote --exit-code --heads origin gh-pages

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add Helm Dependencies
        run: |
          helm repo add etcd https://charts.helm.sh/incubator
          helm repo add zookeeper https://charts.helm.sh/incubator
          helm repo add consul https://charts.helm.sh/stable

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
