name: Create and publish Otp Provider Docker image - V2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
          - sandbox
          - production
      version:
        description: 'Image tag (e.g. v1.2.3)'
        required: true
        default: 'latest'
  push:
    branches:
      - 'dev'

env:
  IMAGE_NAME: bcgov-sso/otp-provider
  TF_VERSION: 1.2.0

jobs:
  build-and-push-image:
    permissions: write-all
    runs-on: ubuntu-24.04

    steps:
      - name: Set global environment variables
        run: |
          cat >> $GITHUB_ENV <<EOF
          TF_VAR_ches_username=${{ secrets.CHES_USERNAME }}
          TF_VAR_ches_password=${{ secrets.CHES_PASSWORD }}
          TF_VAR_otp_cwlogs_group=/aws/ecs/fargate/otp-provider
          TF_STATE_BUCKET_KEY=otp-provider.tfstate
          TF_STATE_BUCKET_REGION=ca-central-1
          EOF
      - name: Set sandbox environment variables
        if: (github.ref == 'refs/heads/dev' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'sandbox')
        run: |
          cat >> $GITHUB_ENV <<EOF
          TF_STATE_BUCKET_NAME=otp-provider-tf-sandbox
          TF_VAR_otp_image_tag=latest
          TF_VAR_subnet_a=Dev-App-A
          TF_VAR_subnet_b=Dev-App-B

          TF_VAR_dev_app_url=https://dev.sandbox.otp.loginproxy.gov.bc.ca
          TF_VAR_dev_custom_domain_name=dev.sandbox.otp.loginproxy.gov.bc.ca
          TF_VAR_dev_cors_origins=https://dev.sandbox.loginproxy.gov.bc.ca
          TF_VAR_dev_task_cpu=256
          TF_VAR_dev_task_memory=512
          TF_VAR_dev_task_container_cpu=256
          TF_VAR_dev_task_container_memory=512
          TF_VAR_dev_task_container_port=3000
          TF_VAR_dev_rds_min_capacity=0
          TF_VAR_dev_rds_max_capacity=2
          TF_VAR_dev_rds_scale_down_time=3600

          TF_VAR_test_app_url=https://test.sandbox.otp.loginproxy.gov.bc.ca
          TF_VAR_test_custom_domain_name=test.sandbox.otp.loginproxy.gov.bc.ca
          TF_VAR_test_cors_origins=https://test.sandbox.loginproxy.gov.bc.ca
          TF_VAR_test_task_cpu=256
          TF_VAR_test_task_memory=512
          TF_VAR_test_task_container_cpu=256
          TF_VAR_test_task_container_memory=512
          TF_VAR_test_task_container_port=3000
          TF_VAR_test_rds_min_capacity=0
          TF_VAR_test_rds_max_capacity=2
          TF_VAR_test_rds_scale_down_time=3600

          TF_VAR_prod_app_url=https://sandbox.otp.loginproxy.gov.bc.ca
          TF_VAR_prod_custom_domain_name=sandbox.otp.loginproxy.gov.bc.ca
          TF_VAR_prod_cors_origins=https://sandbox.loginproxy.gov.bc.ca
          TF_VAR_prod_task_cpu=256
          TF_VAR_prod_task_memory=512
          TF_VAR_prod_task_container_cpu=256
          TF_VAR_prod_task_container_memory=512
          TF_VAR_prod_task_container_port=3000
          TF_VAR_prod_rds_min_capacity=0
          TF_VAR_prod_rds_max_capacity=2
          TF_VAR_prod_rds_scale_down_time=3600
          TF_VAR_enable_grafana=false
          TF_VAR_grafana_kc_url=${{secrets.DEV_KEYCLOAK_BASE_URL}}
          TF_VAR_grafana_kc_client_id=${{secrets.DEV_GRAFANA_OAUTH_CLIENT_SECRET}}
          TF_VAR_grafana_kc_client_secret=${{secrets.DEV_GRAFANA_OAUTH_CLIENT_ID}}
          EOF

      - name: Set env to production
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
        run: |
          cat >> $GITHUB_ENV <<EOF
          TF_STATE_BUCKET_NAME=otp-provider-tf-production
          TF_VAR_otp_image_tag=${{ github.event.inputs.version || 'latest' }}
          TF_VAR_subnet_a=Prod-App-A
          TF_VAR_subnet_b=Prod-App-B

          TF_VAR_dev_app_url=https://dev.otp.loginproxy.gov.bc.ca
          TF_VAR_dev_custom_domain_name=dev.otp.loginproxy.gov.bc.ca
          TF_VAR_dev_cors_origins=https://dev.loginproxy.gov.bc.ca
          TF_VAR_dev_task_cpu=256
          TF_VAR_dev_task_memory=512
          TF_VAR_dev_task_container_cpu=256
          TF_VAR_dev_task_container_memory=512
          TF_VAR_dev_task_container_port=3000
          TF_VAR_dev_rds_min_capacity=0.5
          TF_VAR_dev_rds_max_capacity=2
          TF_VAR_dev_rds_scale_down_time=36000

          TF_VAR_test_app_url=https://test.otp.loginproxy.gov.bc.ca
          TF_VAR_test_custom_domain_name=test.otp.loginproxy.gov.bc.ca
          TF_VAR_test_cors_origins=https://test.loginproxy.gov.bc.ca
          TF_VAR_test_task_cpu=256
          TF_VAR_test_task_memory=512
          TF_VAR_test_task_container_cpu=256
          TF_VAR_test_task_container_memory=512
          TF_VAR_test_task_container_port=3000
          TF_VAR_test_rds_min_capacity=0.5
          TF_VAR_test_rds_max_capacity=2
          TF_VAR_test_rds_scale_down_time=36000

          TF_VAR_prod_app_url=https://otp.loginproxy.gov.bc.ca
          TF_VAR_prod_custom_domain_name=otp.loginproxy.gov.bc.ca
          TF_VAR_prod_cors_origins=https://loginproxy.gov.bc.ca
          TF_VAR_prod_task_cpu=256
          TF_VAR_prod_task_memory=512
          TF_VAR_prod_task_container_cpu=256
          TF_VAR_prod_task_container_memory=512
          TF_VAR_prod_task_container_port=3000
          TF_VAR_prod_rds_min_capacity=0.5
          TF_VAR_prod_rds_max_capacity=2
          TF_VAR_prod_rds_scale_down_time=36000
          TF_VAR_enable_grafana=true
          TF_VAR_grafana_kc_url=${{secrets.PROD_KEYCLOAK_BASE_URL}}
          TF_VAR_grafana_kc_client_id=${{secrets.PROD_GRAFANA_OAUTH_CLIENT_SECRET}}
          TF_VAR_grafana_kc_client_secret=${{secrets.PROD_GRAFANA_OAUTH_CLIENT_ID}}
          EOF
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Dev Credentials
        if: (github.ref == 'refs/heads/dev' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'sandbox')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SANDBOX_SSO_AWS_GH_ACTIONS_DEPLOYER }}
          aws-region: ca-central-1

      - name: Configure AWS Prod Credentials
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PROD_SSO_AWS_GH_ACTIONS_DEPLOYER }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.event.inputs.version || 'latest' }}
        run: |
          echo "Building and pushing Docker image to ECR..."
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        working-directory: ./docker/otp-provider

      - name: Terraform Variables
        run: |
          cat >"config.tf" <<EOF
          terraform {
            backend "s3" {
              bucket         = "${{ env.TF_STATE_BUCKET_NAME }}"
              key            = "${{ env.TF_STATE_BUCKET_KEY }}"
              region         = "${{ env.TF_STATE_BUCKET_REGION }}"
              use_lockfile   = true
            }
          }
          EOF
        working-directory: ./docker/otp-provider/terraform-v2

      - name: Terraform Init
        id: init
        run: terraform init -upgrade
        working-directory: ./docker/otp-provider/terraform-v2

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./docker/otp-provider/terraform-v2
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
        working-directory: ./docker/otp-provider/terraform-v2
