name: Create and publish Keycloak Docker image - Dev

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  GITHUB_REGISTRY: ghcr.io
  REDHAT_REGISTRY: registry.redhat.io
  IMAGE_NAME: bcgov/sso

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the REDHAT Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REDHAT_REGISTRY }}
          username: ${{ secrets.REDHAT_USERNAME }}
          password: ${{ secrets.REDHAT_PASSWORD }}

      - name: Extract Keycloak version from Dockerfile
        if: github.ref == 'refs/heads/main'
        run: |
          KEYCLOAK_VERSION=$(sed -n 's/ENV KEYCLOAK_VERSION=\([^ ]*\)/\1/p' Dockerfile-26)
          echo "Extracted version: $KEYCLOAK_VERSION"
          git fetch --tags
          LATEST_BUILD=$(git tag -l "v${KEYCLOAK_VERSION}-build.*" \
          | sed -E "s/v${KEYCLOAK_VERSION}-build\.//" \
          | sort -n \
          | tail -1)
          if [ -z "$LATEST_BUILD" ]; then
          NEXT_BUILD=1
          else
          NEXT_BUILD=$((LATEST_BUILD + 1))
          fi
          NEXT_TAG="v${KEYCLOAK_VERSION}-build.${NEXT_BUILD}"
          echo "Next release tag: $NEXT_TAG"
          echo "NEXT_TAG=${NEXT_TAG}" >> $GITHUB_ENV
        working-directory: docker/keycloak

      - name: Set Image Tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TAG=${{ env.NEXT_TAG }}" >> $GITHUB_ENV
            git tag ${{ env.NEXT_TAG }}
            git push origin ${{ env.NEXT_TAG }}
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi
          echo "Using tag: $TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/keycloak
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/${{env.IMAGE_NAME}}:${{ env.TAG }}
          file: docker/keycloak/Dockerfile-26
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: Release ${{ env.NEXT_TAG }}
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
