name: Set the dr deployment to standby

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev", "c6af30-test", "c6af30-prod"]

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: sha-${{ github.sha }}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}

jobs:
  set-dr-to-standby:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list files
        run: ls ./
      - name: Log into golddr and remove patroni standby
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}
          namespace: ${{ github.event.inputs.namespace }}
          insecure_skip_tls_verify: true
      - name: Confirm Patroni Gold is active
        run: |
          echo "Not Done Yet"
        shell: bash
      # - name: Deploy keycloak-dr in standby mode
      #   run: |
      #     chmod +x ./helm/keycloak/transition-scripts/deploy-golddr-standby.sh
      #     ./helm/keycloak/transition-scripts/deploy-golddr-standby.sh ${{ github.event.inputs.namespace }}
      #   shell: bash
      - name: Set patroni-dr to standby
        run: |
          oc rsh -n ${{ github.event.inputs.namespace }} sso-patroni-0 \
          curl -s -XPATCH -d '{  "standby_cluster": {"create_replica_methods": ["basebackup_fast_xlog"],"host": "sso-patroni-gold.c6af30-test.svc.cluster.local","port": 56583}}' http://localhost:8008/config | jq .
        shell: bash


        