name: Set the dr deployment to active

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev", "c6af30-test", "c6af30-prod"]

jobs:
  set-dr-to-active:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.dractivation.outputs.patroniconfig }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into golddr and remove patroni standby
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}
          namespace: ${{ github.event.inputs.namespace }}
          insecure_skip_tls_verify: true
      - name: Set patroni-dr to primary
        id: dractivation
        run: |
          chmod +x ./keycloak/transition-scripts/set-patroni-dr-active.sh
          ./keycloak/transition-scripts/set-patroni-dr-active.sh ${{ github.event.inputs.namespace }}
        shell: bash
        working-directory: helm
      # - name: Deploy keycloak-dr in active mode
      #   run: |
      #     chmod +x ./keycloak/transition-scripts/deploy-golddr-active.sh
      #     ./keycloak/transition-scripts/deploy-golddr-active.sh ${{ github.event.inputs.namespace }}
      #   shell: bash
      #   working-directory: helm
  deploy-kc-in-dr:
    runs-on: ubuntu-latest
    needs: set-dr-to-active
    if: ${{needs.set-dr-to-active.outputs.output1}} == '200'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy keycloak-dr in active mode
        run: |
          chmod +x ./keycloak/transition-scripts/deploy-golddr-active.sh
          ./keycloak/transition-scripts/deploy-golddr-active.sh ${{ github.event.inputs.namespace }}
        shell: bash
        working-directory: helm