name: Set the dr deployment to active

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev", "c6af30-test", "c6af30-prod"]

jobs:
  set-dr-to-active:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into golddr and remove patroni standby
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}
          namespace: ${{ github.event.inputs.namespace }}
          insecure_skip_tls_verify: true
      - name: Set patroni-dr to primary
        run: |
          oc rsh -n ${{ github.event.inputs.namespace }} sso-patroni-0 curl -s -XPATCH -d '{  "standby_cluster":null}' http://localhost:8008/config | jq .
        shell: bash
      - name: Deploy keycloak-dr in active mode
        run: |
          chmod +x ./transition-scripts/deploy-golddr-active.sh
          ./transition-scripts/deploy-golddr-active.sh ${{ github.event.inputs.namespace }}
        shell: bash
        working-directory: helm/keycloak 
