name: Set the dr deployment to standby

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev", "c6af30-test", "c6af30-prod"]
      patroni-port:
        description: "The port used for tsc between gold and gold-dr"
        required: true
        options: [56583]

jobs:
  check-patroni-dr-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into gold dr
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}
          namespace: ${{ github.event.inputs.namespace }}
          insecure_skip_tls_verify: true
      - name: Check that sso-patroni dr is active
        id: golddractive
        run: |
          chmod +x ./keycloak/transition-scripts/check-patroni-active.sh
          ./keycloak/transition-scripts/check-patroni-active.sh ${{ github.event.inputs.namespace }} golddr
        shell: bash
        working-directory: helm
  # set-patroni-dr-to-standby:
  #   runs-on: ubuntu-latest
  #   needs: check-patroni-gold-active
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Log into golddr and set patroni standby
  #       uses: redhat-actions/oc-login@v1
  #       with:
  #         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
  #         openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}
  #         namespace: ${{ github.event.inputs.namespace }}
  #         insecure_skip_tls_verify: true
  #     - name: Deploy keycloak-dr in standby mode
  #       run: |
  #         chmod +x ./helm/keycloak/transition-scripts/deploy-golddr-standby.sh
  #         ./helm/keycloak/transition-scripts/deploy-golddr-standby.sh ${{ github.event.inputs.namespace }}
  #       shell: bash
  #     - name: Set patroni-dr to standby
  #       run: |
  #         chmod +x ./keycloak/transition-scripts/set-patroni-dr-standby.sh
  #         ./keycloak/transition-scripts/set-patroni-dr-standby.sh ${{ github.event.inputs.namespace }} ${{ github.event.inputs.patroni-port }}
  #       shell: bash
  #       working-directory: helm
