name: Run Siteminder Tests to Validate SAML Payload

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment under test'
        required: true
        default: 'prod'
        type: choice
        options: ['dev', 'test', 'prod']
      cluster:
        description: 'OCP'
        required: true
        default: 'gold'
        type: choice
        options: ['silver', 'gold']

jobs:
  run-siteminder-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run siteminder tests
        run: |
          cd ${{ github.workspace }}/siteminder-tests
          echo "${{ secrets.SITEMINDER_TESTS_ENV }}" | base64 --decode > .env
          docker run --rm -e ENVIRONMENT=${{ github.event.inputs.environment }} -e CLUSTER=${{ github.event.inputs.cluster }} -v $(pwd)/results:/app/results $(docker build -q .)
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.cluster }}-${{ github.event.inputs.environment }}-results
          path: ${{ github.workspace }}/siteminder-tests/results
