name: Run script to fetch SAML attributes

on: workflow_dispatch

jobs:
  run-siteminder-script:
    name: Fetch Attributes from SAML Response
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Generate env file
        run: |
          cd ${{ github.workspace }}/cy-siteminder-tests
          echo "${{ secrets.SITEMINDER_TESTS_ENV }}" | base64 --decode > .env
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-test-cache
          key: ${{ runner.os }}-buildx-test-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-test-
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: cy-siteminder-tests/
          push: false
          load: true
          tags: siteminder-tests
          cache-from: type=local,src=/tmp/.buildx-test-cache
          cache-to: type=local,dest=/tmp/.buildx-test-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-test-cache
          mv /tmp/.buildx-test-cache-new /tmp/.buildx-test-cache
      - name: Run siteminder tests
        run: |
          cd ${{ github.workspace }}/cy-siteminder-tests
          docker run --rm -v $(pwd)/results:/e2e/results siteminder-tests cy:run:attrs
